mode: "run_window_test"

window_test_flybys: ["GALILEO", "ROSETTA_2005", "NEAR",
                        "MESSENGER", "CASSINI", "ROSETTA_2009", "JUNO", 
                        "GALILEO_2", "ROSETTA_2007"]

window_test_phi_offsets: 36
window_test_max_distance: 2e5 # km
